### PR TITLE
Bug: updated tests

### PR DESCRIPTION
**Pull request by MelSumner**
This will end up being a major because we had to bump the node version.

Changes:
- updated the package.json file so the scripts were sorted alphabetically. 
- consolidated node versions to latest LTS
- updated specific dependencies
- removed the 3.25 scenario
- moved from testdouble to sinon

CleanShot 2024-01-22 at 19 34 56@2x

CleanShot 2024-01-23 at 09 49 48

Everything is passing locally but not here, so I think we need to figure out what must pass to get the next release out, and then what needs to be fixed after that.

### CODE REVIEW

**Comment by knownasilya** [comment]
Would this be a major version change since the node version is being updated?

**Review by knownasilya — APPROVED** [review]

**Comment by MelSumner** [comment]
@knownasilya we might need to make it one. 

I'm trying to get the tests to pass and only upgrading what I need to do, in order to make that happen. WDYT?

**Comment by knownasilya** [comment]
I'm fine with bumping a major, plenty of numbers to go around. It'll be an easy upgrade if that's the only change. Looks like the GH actions workflow is busted too.

**Comment by MelSumner** [comment]
Yeah, I just looked at it and I have no idea why. It looks like it should be fine?

**Comment by knownasilya** [comment]
Yes a major would be required for that. Probably need to upgrade node for CI too.

**Review by ef4 — COMMENTED** [review]
I also don't see why these tests were passing before, but I think the fix here won't last. Once the month rolls over they would start failing again. 

Here is an alternative solution that I think will be more permanent: https://github.com/ef4/ember-pikaday/commit/04437abea0826f21b219b4bcdcaf7e2c5947363a

**Comment by knownasilya** [comment]
Nice @MelSumner

**Pull request merged**
